# DataFrame Index

## Index란?
- Pandas의 Index는 데이터프레임과 시리즈의 각 행(row)를 고유하게 식별하는 역할을 수행함
- 관계형 데이터베이스의 Primary key(pk)와 유사한 개념
- 특징
  - 데이터 식별 역할 수행
  - 숫자, 문자열도 가능
  - 생성 후 직접 수정 불가
  - reset_index() 함수를 이용하여 재생성 가능

In [1]:
import warnings
warnings.filterwarnings(action='ignore')

import pandas as pd
import numpy as np

## 1. Index 객체

In [3]:
# Titanic 데이터셋 로드
titanic_df = pd.read_csv('data/titanic/train.csv')
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [4]:
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [6]:
# Index 객체 추출
td_indexes = titanic_df.index
td_indexes

RangeIndex(start=0, stop=891, step=1)

In [7]:
type(td_indexes)

pandas.core.indexes.range.RangeIndex

In [8]:
td_indexes.shape

(891,)

In [ ]:
td_indexes.values

In [15]:
# Index 객체 정보 
print(f"type : {type(td_indexes)}")
print(f"shape : {td_indexes.values.shape}")
print(f"shape : {td_indexes.shape}")

print(f"Index 슬라이싱 : {td_indexes[:5].values}")
print(f"Index 슬라이싱 : {td_indexes.values[:5]}")

print(f"특정 Index 조회 : {td_indexes[5]}")
print(f"size 조회 : {td_indexes.size}")
print(f"is_unique : {td_indexes.is_unique}")

type : <class 'pandas.core.indexes.range.RangeIndex'>
shape : (891,)
shape : (891,)
Index 슬라이싱 : [0 1 2 3 4]
Index 슬라이싱 : [0 1 2 3 4]
특정 Index 조회 : 5
size 조회 : 891
is_unique : True

In [ ]:
# 생성된 Index 객체는 수정 불가, TypeError: Index does not support mutable operations ❌
# Index는 수정이 안되는 불변 객체임
td_indexes[0] = 100

## 2. Index 기반 연산 방식
- ✨ 판다스는 인덱스 이름을 기준으로 데이터를 맞춘 후 연산함

### (1) Series 연산
- ✨ 동일한 인덱스를 가진 데이터끼리만 연산됨

####  기본 Series 생성 및 연산

In [20]:
# Series 생성
s1 = pd.Series([10, 20, 30])
s2 = pd.Series([10, 20, 30])
print(s1, '\n', s2)

0    10
1    20
2    30
dtype: int64
 0    10
1    20
2    30
dtype: int64

In [ ]:
# Series 사칙 연산
print(s1 + s2)
print(s1 - s2)
print(s1 * s2)
print(s1 / s2)

#### Index 지정

In [22]:
s1 = pd.Series([10, 20, 30], 
                index=['a', 'b', 'c'])
s2 = pd.Series([10, 20, 30], 
                index=['b', 'c', 'd'])
print(s1, '\n', s2)

a    10
b    20
c    30
dtype: int64
 b    10
c    20
d    30
dtype: int64

#### Index 기준 연산 - 동일한 인덱스끼리 연산 진행

In [23]:
# Series 사칙 연산 - 동일한 인덱스 기준으로 연산이 진행됨
print(s1 + s2)
print(s1 - s2)
print(s1 * s2)
print(s1 / s2)

a     NaN
b    30.0
c    50.0
d     NaN
dtype: float64
a     NaN
b    10.0
c    10.0
d     NaN
dtype: float64
a      NaN
b    200.0
c    600.0
d      NaN
dtype: float64
a    NaN
b    2.0
c    1.5
d    NaN
dtype: float64

### (2) DataFrame 연산
- ✨ 동일한 인덱스, 동일한 컬럼명 기준으로 연산이 진행됨

#### DataFrame 생성

In [26]:
df1 = pd.DataFrame(
    {
        'col1' : [10, 20, 30],
        'col2' : [10, 20, 30]
    },
    index=['a', 'b', 'c']
)

In [27]:
df2 = pd.DataFrame(
    {
        'col1' : [10, 20, 30],
        'col3' : [10, 20, 30]
    },
    index=['a', 'b', 'c']
)

In [28]:
print(df1)
print()
print(df2)

   col1  col2
a    10    10
b    20    20
c    30    30

   col1  col3
a    10    10
b    20    20
c    30    30

In [29]:
# 인덱스, 컬럼명이 일치해야만 연산이 수행됨
df1 + df2

   col1  col2  col3
a    20   NaN   NaN
b    40   NaN   NaN
c    60   NaN   NaN

In [32]:
# df1 객체에 col3 컬럼을 추가, 값 100
df1['col3'] = 100
df1

   col1  col2  col3
a    10    10   100
b    20    20   100
c    30    30   100

In [33]:
df1 + df2

   col1  col2  col3
a    20   NaN   110
b    40   NaN   120
c    60   NaN   130

## 3. reset_index()
- ✨ reset_index() 실행 시 기존 Index는 첫번째 컬럼으로 이동하고, 새로운 숫자의 Index가 생성됨

In [34]:
# 데이터셋 확인
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [37]:
# 인덱스 재생성, reset_index()
td_reset_df = titanic_df.reset_index(inplace=False)
td_reset_df.head()

,index,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [40]:
# td_reset_df 객체의 인덱스 재생성
td_reset_df2 = td_reset_df.reset_index(inplace=False)
td_reset_df2.head(3)

,level_0,index,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [ ]:
# td_reset_df2 객체의 level_0 컬럼 삭제, 원본 반영
td_reset_df2.drop('level_0', axis=1, inplace=True) 
td_reset_df2.head()

In [ ]:
# td_reset_df2 객체의 0, 1, 2 인덱스 삭제, 원본 반영
td_reset_df2.drop([0, 1, 2], axis=0, inplace=True)
td_reset_df2.head()

In [ ]:
# td_reset_df2 객체의 인덱스 재생성, 원본 반영
td_reset_df2.reset_index(inplace=True)
td_reset_df2.head()

In [ ]:
td_reset_df2.drop(['level_0', 'index'], axis=1, inplace=True)
td_reset_df2

## 4. rename() - 컬럼명 변경
- 문법

  DataFrame.rename(columns={'기존 컬럼명' : '신규 컬럼명'})

In [48]:
# Age_0 컬럼 추가, 값은 0
titanic_df['Age_0'] = 0
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0

In [49]:
# Age_0 컬럼의 데이터를 1로 수정
titanic_df['Age_0'] = 1
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1

In [54]:
# Age_0 컬럼명을 Age_1 으로 수정
titanic_df.rename(columns={ 'Age_0': 'Age_1'}, inplace=True)
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_1
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1

In [58]:
# 인덱스 0, 2, 4 => 'a', 'b', 'c' 변경
td_rename = titanic_df.rename(index= {0: "a", 2: "b", 4: "c"})
td_rename.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_1
a,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
b,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
c,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1

In [59]:
td_rename_index = td_rename.index
td_rename_index

Index(['a',   1, 'b',   3, 'c',   5,   6,   7,   8,   9,
       ...
       881, 882, 883, 884, 885, 886, 887, 888, 889, 890],
      dtype='object', length=891)