# 결손 데이터(결측치) 처리

### 결손데이터(결측치)란?
- 결측치(Missing Data)는 값이 존재하지 않는 데이터를 의미
- 판단스에서는 NaN으로 표현됨

** 결측치가 있다면???  어떻게 처리할것인가?? **
1) 실무자와 협의한 후 진행 - 제거도 한 방법!!
2) 평균으로 대체하는 값, 중앙값으로 대체하는 값..
   예) 날짜마다 온도가 저장되어 있는 데이터셋이라면..
    20260601    20
    ...
    20260614    32
    20260615    NaN => 앞, 뒤의 값으로 대체
    20260616    31
    ..
    20260630    36

In [1]:
import warnings
warnings.filterwarnings(action='ignore')

import pandas as pd
import numpy as np

### 1. 결손 데이터 생성

In [2]:
df = pd.DataFrame(
    {
        'Name': ['Smith','Lee','Kim', 'Park'],
        'Age': [20, np.nan, 30, 40],
        'Score': [90, 85, np.nan, 75],
    }
)
df

    Name   Age  Score
0  Smith  20.0   90.0
1    Lee   NaN   85.0
2    Kim  30.0    NaN
3   Park  40.0   75.0

In [3]:
df.shape

(4, 3)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     3 non-null      float64
 2   Score   3 non-null      float64
dtypes: float64(2), object(1)
memory usage: 228.0+ bytes

In [5]:
df.describe()

        Age      Score
count   3.0   3.000000
mean   30.0  83.333333
std    10.0   7.637626
min    20.0  75.000000
25%    25.0  80.000000
50%    30.0  85.000000
75%    35.0  87.500000
max    40.0  90.000000

### 2. 결손 데이터 확인
- isna() = isnull()

In [9]:
df

    Name   Age  Score
0  Smith  20.0   90.0
1    Lee   NaN   85.0
2    Kim  30.0    NaN
3   Park  40.0   75.0

In [ ]:
df.isna()
df.isnull()

In [13]:
# NaN 값이 있는 데이터만 합계로 계산
print(df.isna().sum())
print(df.isnull().sum())

Name     0
Age      1
Score    1
dtype: int64
Name     0
Age      1
Score    1
dtype: int64

### 3. 결손 데이터 삭제
- dropna() : 결손 데이터가 포함된 행 또는 열 삭제

In [16]:
filter_na = df.dropna()
filter_na

    Name   Age  Score
0  Smith  20.0   90.0
3   Park  40.0   75.0

In [17]:
print(df)
print('-'*30)
print(filter_na)

    Name   Age  Score
0  Smith  20.0   90.0
1    Lee   NaN   85.0
2    Kim  30.0    NaN
3   Park  40.0   75.0
------------------------------
    Name   Age  Score
0  Smith  20.0   90.0
3   Park  40.0   75.0

In [18]:
# 결측치 데이터가 포함된 열 삭제
filter_na_cols = df.dropna(axis=1)
print(df)
print('-'*30)
print(filter_na_cols)

    Name   Age  Score
0  Smith  20.0   90.0
1    Lee   NaN   85.0
2    Kim  30.0    NaN
3   Park  40.0   75.0
------------------------------
    Name
0  Smith
1    Lee
2    Kim
3   Park

In [20]:
# 결측치가 저장된 특정 컬럼만 삭제
df.dropna(axis=0, subset=['Age'])

    Name   Age  Score
0  Smith  20.0   90.0
2    Kim  30.0    NaN
3   Park  40.0   75.0

In [21]:
# Addr 컬럼 추가, 값은 모두 결측치(NaN)
df['Addr'] = np.nan
df

    Name   Age  Score  Addr
0  Smith  20.0   90.0   NaN
1    Lee   NaN   85.0   NaN
2    Kim  30.0    NaN   NaN
3   Park  40.0   75.0   NaN

In [22]:
# 모든 데이터가 결측치인 컬럼 삭제
df.dropna(how='all', axis=1, inplace=True)
df

    Name   Age  Score
0  Smith  20.0   90.0
1    Lee   NaN   85.0
2    Kim  30.0    NaN
3   Park  40.0   75.0

In [23]:
# 하나라도 결측치를 포함한 경우 삭제 how='any', axis=0, inplace=False
df.dropna(how='any', axis=0, inplace=False)

    Name   Age  Score
0  Smith  20.0   90.0
3   Park  40.0   75.0

### 4. 결손 데이터 대체
- fillna() : 결손 데이터를 특정값으로 대체

In [28]:
# 결손 데이터를 0으로 모두 대체
df.fillna(0)

    Name   Age  Score
0  Smith  20.0   90.0
1    Lee   0.0   85.0
2    Kim  30.0    0.0
3   Park  40.0   75.0

In [31]:
# 결손 데이터를 'Unknown'으로 모두 대체
df_str = df.fillna('Unknown')
df_str.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      object
 2   Score   4 non-null      object
dtypes: object(3)
memory usage: 228.0+ bytes

In [37]:
# Age 컬럼의 결손 데이터만 0으로 대체
df['Age'] = df['Age'].fillna(0)

In [38]:
df

    Name   Age  Score
0  Smith  20.0   90.0
1    Lee   0.0   85.0
2    Kim  30.0    NaN
3   Park  40.0   75.0

### 5. 평균값으로 대체

In [39]:
df = pd.DataFrame(
    {
        'Name': ['Smith','Lee','Kim', 'Park'],
        'Age': [20, np.nan, 30, 40],
        'Score': [90, 85, np.nan, 75],
    }
)
df

    Name   Age  Score
0  Smith  20.0   90.0
1    Lee   NaN   85.0
2    Kim  30.0    NaN
3   Park  40.0   75.0

In [43]:
# Age 컬럼의 결손 데이터를 평균값으로 대체
age_mean = df['Age'].mean()
age_mean

np.float64(30.0)

In [46]:
df['Age'] = df['Age'].fillna(age_mean)
df

    Name   Age  Score
0  Smith  20.0   90.0
1    Lee  30.0   85.0
2    Kim  30.0    NaN
3   Park  40.0   75.0

In [47]:
# Score 컬럼의 결측치를 평균값으로 대체
df['Score'] = df['Score'].fillna(df['Score'].mean()) 
df

    Name   Age      Score
0  Smith  20.0  90.000000
1    Lee  30.0  85.000000
2    Kim  30.0  83.333333
3   Park  40.0  75.000000

### 6. 최빈값으로 대체
- 가장 많이 등장하는 값으로 대체
- mode() : 가장 많이 등장한 값 반환

In [48]:
df = pd.DataFrame(
    {
        'Name': ['Smith','Lee','Kim', 'Park'],
        'Age': [20, np.nan, 30, 40],
        'Score': [90, 85, np.nan, 75],
    }
)
df

    Name   Age  Score
0  Smith  20.0   90.0
1    Lee   NaN   85.0
2    Kim  30.0    NaN
3   Park  40.0   75.0

In [53]:
# Age 컬럼의 최빈값 조회
df['Age'].mode()[0]

np.float64(20.0)

In [56]:
# Age 컬럼의 결측치를 최빈값 대체
df['Age'] = df['Age'].fillna(df['Age'].mode()[0])
df

    Name   Age  Score
0  Smith  20.0   90.0
1    Lee  20.0   85.0
2    Kim  30.0    NaN
3   Park  40.0   75.0

### 7. 이전 데이터로 대체
- ffill : forward fill

In [57]:
df = pd.DataFrame(
    {
        'Name': ['Smith','Lee','Kim', 'Park'],
        'Age': [20, np.nan, 30, 40],
        'Score': [90, 85, np.nan, 75],
    }
)
df

    Name   Age  Score
0  Smith  20.0   90.0
1    Lee   NaN   85.0
2    Kim  30.0    NaN
3   Park  40.0   75.0

In [58]:
# Age, Score 컬럼의 결측치를 ffill 함수로 대체
df.ffill()

    Name   Age  Score
0  Smith  20.0   90.0
1    Lee  20.0   85.0
2    Kim  30.0   85.0
3   Park  40.0   75.0

### 8. 다음 데이터로 대체
- bfill : backward fill

In [61]:
# Age, Score 컬럼의 결측치를 다음 값으로 대체
df.bfill()

    Name   Age  Score
0  Smith  20.0   90.0
1    Lee  30.0   85.0
2    Kim  30.0   75.0
3   Park  40.0   75.0

In [65]:
# Age 컬럼을 다음 값으로 대체
df['Age'] = df['Age'].bfill()
df

    Name   Age  Score
0  Smith  20.0   90.0
1    Lee  30.0   85.0
2    Kim  30.0    NaN
3   Park  40.0   75.0

### 9. Titanic 데이터 결측치 처리

In [67]:
# 데이터 로드
titanic_df = pd.read_csv('data/titanic/train.csv')
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [68]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [75]:
# 결측치 확인
#titanic_df.isna().sum()
titanic_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [79]:
# Cabin 컬럼의 687개의 결측 데이터는 '0000'로 대체
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('0000')

In [81]:
titanic_df.head()
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin            0
Embarked         2
dtype: int64

In [90]:
# Age 컬럼은 평균값을 구해 결측 데이터를 대체
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       2
dtype: int64

In [93]:
# Embarked의 결측치를 최빈값으로 대체
titanic_df['Embarked'].mode()[0]
titanic_df['Embarked'] = titanic_df['Embarked'].fillna(titanic_df['Embarked'].mode()[0])

In [94]:
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

### 10. nunique & replace

#### (1) nuique

In [95]:
# value_counts() => 범주형 데이터 조회
titanic_df['Embarked'].value_counts()

Embarked
S    646
C    168
Q     77
Name: count, dtype: int64

In [101]:
# titanic_df['PassengerId'].value_counts()
print(titanic_df['PassengerId'].nunique())
print(titanic_df['Pclass'].nunique())   # 범주형
print(titanic_df['Survived'].nunique()) # 범주형

891
3
2

#### (2) replace
- 원본값을 다른값으로 대체

In [103]:
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,0000,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,0000,S

In [105]:
# Cabin의 '0000' 값을 'C000' 값으로 대체
titanic_df['Cabin'] = titanic_df['Cabin'].replace('0000', 'C000')
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,C000,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,C000,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,C000,S